spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graproject?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true


mybatis:
  typeAliasesPackage: com.oauth.mapper #指向实体类包路径
  mapperLocations: classpath:mapper/*.xml #classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件

# tk配置
mapper:
  mappers:  tk.mybatis.mapper.common.Mapper
  not-empty: false
  before: true
  identity: MYSQL