# 服务名称
spring:
  application:
    name: spring-cloud-gateway
  # 开启 Gateway 服务注册中心服务发现
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graproject?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
# Eureka Server 配置
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug

mybatis:
  typeAliasesPackage: com.gateway.mapper #指向实体类包路径
  mapperLocations: classpath:mapper/*.xml #classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件

# tk配置
mapper:
  mappers:  tk.mybatis.mapper.common.Mapper
  not-empty: false
  before: true
  identity: MYSQL